# Generated by Django 4.2.23 on 2025-07-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('terrains', models.JSONField(blank=True, null=True)),
                ('climates', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
